config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :case do
    get 'home', to: 'home#index'
    resources :cases
    resources :components, only: [:create, :update, :destroy]
    resources :relations, only: [:create, :update, :destroy]
  end

  namespace :state do
    get 'home', to: 'home#index'
    resources :machines
    resources :transitions, only: [:create, :update, :destroy]
    resources :elements, only: [:create, :update, :destroy]
  end

  devise_for :users

end

app/models/case.rb
class Case < ActiveRecord::Base
  belongs_to :user
  has_many :components
  has_many :relations
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :case
  belongs_to :mold
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  has_many :relations
end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :machine
  belongs_to :type
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  belongs_to :user
  has_many :elements
  has_many :transitions
end

app/models/mold.rb
class Mold < ActiveRecord::Base
  has_many :components
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :case
  belongs_to :connection
end

app/models/transition.rb
class Transition < ActiveRecord::Base
  belongs_to :machines
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Associações
  has_many :machine
  has_many :case_diagrams

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set Layout
  layout :layout_by_resource

  protected
    def layout_by_resource
    if devise_controller? && resource_name == :user
      "application_devise"
    else
      "application"
    end
  end
end

app/controllers/case_controller.rb
class CaseController < ApplicationController
  layout 'casediagram'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/state_controller.rb
class StateController < ApplicationController
  layout 'statediagram'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case/actors_helper.rb
module Case::ActorsHelper
end

app/helpers/case/collies_helper.rb
module Case::ColliesHelper
end

app/helpers/case/home_helper.rb
module Case::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/state/home_helper.rb
module State::HomeHelper
end

app/views/layouts/shared/_footer.html.erb
<div id="footer">
  <p>UML BLINDFOLDED 2017</p>
</div>

app/views/layouts/shared/_header.html.erb
<div class="row">
  <div class="col-md-12 text-center">

    <div class="div_title">
      <img src="/img/Blindfolded_logo.png" alt="" class="img_title">
    </div>

    <div class="div_title">
      <h1 class="title">
        <span class="LeelaUIb_font">Blind</span><span class="Leelaw_font">Folded</span>
      </h1>
    </div>
  </div>
</div>
<hr class="hr_login">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

app/views/layouts/shared/_menu_case.html.erb
<div class="col-md-3">
  <div class="menu_title">
    <p>Caso de Uso</p>
  </div>
  <div class="navbar-default sidebar navbar-style" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav in" id="side-menu">
            <li>
              <%= link_to "#{'<i class="fa fa-home fa-fw"></i>'} #{t('buttons.home')}".html_safe, root_path, class:"active a-style" %>
            </li>
            <li>
              <%= link_to "#{'<i class="fa fa-table fa-fw"></i>'} #{t('buttons.list_diagram')}".html_safe, case_cases_path, class:"active a-style" %>
            </li>
            <li>
              <%= link_to "#{'<i class="fa fa-plus fa-fw"></i>'} #{t('buttons.new_diagram')}".html_safe, new_case_case_path, class:"active a-style" %>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>


</div>

app/views/layouts/shared/_menu_home.html.erb
<div class="col-md-3">
  <div class="menu_title">
    <p>BlindFolded</p>
  </div>
  <div class="navbar-default sidebar navbar-style" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav in" id="side-menu">
            <li>
              <%= link_to "#{'<i class="fa fa-home fa-fw"></i>'} #{t('buttons.home')}".html_safe, root_path, class:"active a-style" %>
            </li>
            <li>
              <%= link_to "#{'<i class="glyphicon glyphicon-retweet fa-fw"></i>'} #{t('buttons.state')}".html_safe, state_home_path, class:"active a-style" %>
            </li>
            <li>
              <%= link_to "#{'<i class="fa fa-male fa-fw"></i>'} #{t('buttons.case')}".html_safe, case_home_path, class:"active a-style" %>
            </li>
            <li>
              <%= link_to "#{'<i class="glyphicon glyphicon-log-out fa-fw"></i>'} #{t('buttons.logout')}".html_safe, destroy_user_session_path, method: :delete, class:"active a-style" %>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>


</div>

app/views/layouts/shared/_menu_state.html.erb
<div class="col-md-3">
  <div class="menu_title">
    <p>Máquina de Estado</p>
  </div>
  <div class="navbar-default sidebar navbar-style" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav in" id="side-menu">
            <li>
              <%= link_to "#{'<i class="fa fa-home fa-fw"></i>'} #{t('buttons.home')}".html_safe, root_path, class:"active a-style" %>
            </li>
            <li>
              <%= link_to "#{'<i class="fa fa-table fa-fw"></i>'} #{t('buttons.list_diagram')}".html_safe, state_machines_path, class:"active a-style" %>
            </li>
            <li>
              <%= link_to "#{'<i class="fa fa-plus fa-fw"></i>'} #{t('buttons.new_diagram')}".html_safe, new_state_machine_path, class:"active a-style" %>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>


</div>