config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :case do
    get 'home', to: 'home#index'
    resources :cases
    resources :components, only: [:create, :update, :destroy]
    resources :relations, only: [:create, :update, :destroy]
  end

  namespace :state do
    get 'home', to: 'home#index'
    resources :machines
    resources :transitions, only: [:create, :update, :destroy]
    resources :elements, only: [:create, :update, :destroy]
  end

  devise_for :users

end

app/models/case.rb
class Case < ActiveRecord::Base
  belongs_to :user
  has_many :components
  has_many :relations
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :case
  belongs_to :mold
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  has_many :relations
end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :machine
  belongs_to :type
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  belongs_to :user
  has_many :elements
  has_many :transitions
end

app/models/mold.rb
class Mold < ActiveRecord::Base
  has_many :components
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :case
  belongs_to :connection
end

app/models/transition.rb
class Transition < ActiveRecord::Base
  belongs_to :machines
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Associações
  has_many :machine
  has_many :case_diagrams

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set Layout
  layout :layout_by_resource

  protected
    def layout_by_resource
    if devise_controller? && resource_name == :user
      "application_devise"
    else
      "application"
    end
  end
end

app/controllers/case_controller.rb
class CaseController < ApplicationController
  layout 'casediagram'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/state/elements_controller.rb
class State::ElementsController < StateController
  before_action :set_state_element, only: [:update, :destroy]

  def create
    @element = Element.new(element_params)
    respond_to do |format|
      if @element.save
        format.html { redirect_to edit_state_machine_path(@element.machine_id), notice: 'Elemento criado com sucesso.' }
      end
    end
  end

  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to edit_state_machine_path(@element.machine_id), notice: 'Elemento atualizado com sucesso.' }
      end
    end
  end

  def destroy
    if @element.destroy
      respond_to do |format|
        format.html { redirect_to edit_state_machine_path(@element.machine_id), notice: 'Elemento deletado com sucesso.' }
      end
    end
  end

  private
    def set_state_element
      @element = Element.find(params[:id])
    end

    def element_params
      params.permit(:nameElem, :descriptionElem, :machine_id, :type_id);
    end
end

app/controllers/state/home_controller.rb
class State::HomeController < StateController
  def index
  end
end

app/controllers/state/machines_controller.rb
class State::MachinesController < StateController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]
  before_action :config_table, only: [:show, :edit]

  def index
    @machines = Machine.where(user_id: current_user)
  end

  def show
  end

  def new
    @machine = Machine.new
  end

  def edit
    @machine_status = @machine.elements.where(type_id: 1)
  end

  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to edit_state_machine_path(@machine), notice: 'Diagrama criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to edit_state_machine_path(@machine), notice: 'Diagrama atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    if @machine.destroy
      respond_to do |format|
        format.html { redirect_to state_machines_path, notice: 'Diagrama deletado com sucesso.' }
      end
    end
  end

  private
    def set_machine
      @machine = Machine.find(params[:id])
    end

    def machine_params
      params.require(:machine).permit(:nameDiagram, :elemInitial, :elemEnd, :user_id)
    end

    def config_table
      @options_type = Type.all
      @options_elements = Element.where(machine_id: @machine.id)
    end
end

app/controllers/state/transitions_controller.rb
class State::TransitionsController < StateController
  before_action :set_state_transition, only: [:update, :destroy]

  def create
    @transition = Transition.new(transition_params)
    respond_to do |format|
      if @transition.save
        format.html { redirect_to edit_state_machine_path(@transition.machine_id), notice: 'Transição criada com sucesso.' }
      end
    end
  end

  def update
    respond_to do |format|
      if @transition.update(transition_params)
        format.html { redirect_to edit_state_machine_path(@transition.machine_id), notice: 'Transição atualizada com sucesso.' }
      end
    end
  end

  def destroy
    if @transition.destroy
      respond_to do |format|
        format.html { redirect_to edit_state_machine_path(@transition.machine_id), notice: 'Transição deletada com sucesso.' }
      end
    end
  end

  private
    def set_state_transition
      @transition = Transition.find(params[:id])
    end

    def transition_params
      params.permit(:elemStart, :elemEnd, :descriptionTran, :machine_id);
    end
end

app/controllers/state_controller.rb
class StateController < ApplicationController
  layout 'statediagram'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case/actors_helper.rb
module Case::ActorsHelper
end

app/helpers/case/collies_helper.rb
module Case::ColliesHelper
end

app/helpers/case/components_helper.rb
module Case::ComponentsHelper
end

app/helpers/case/diagrams_helper.rb
module Case::DiagramsHelper
end

app/helpers/case/home_helper.rb
module Case::HomeHelper
end

app/helpers/case/relations_helper.rb
module Case::RelationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/state/diagrams_helper.rb
module State::DiagramsHelper
end

app/helpers/state/elements_helper.rb
module State::ElementsHelper
end

app/helpers/state/home_helper.rb
module State::HomeHelper
end

app/helpers/state/transitions_helper.rb
module State::TransitionsHelper
end

app/views/state/machines/edit.html.erb
<h1><%= t('messages.edit_diagram') %></h1>
<hr>

<%= form_for([:state, @machine]) do |f| %>
  <% if @machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% @machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="col-md-8 col-md-offset-1">
      <div class="row">
        <div class="field pull-left">
          <%= f.label :nameDiagram %><br>
          <%= f.text_field :nameDiagram, class:"form-control " %>
        </div>
        <div class="pull-right bt-edit">
          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalDiagrama"><%= t('buttons.generate_diagram') %></button>
        </div>
      </div><hr>
    </div>

    <% if @machine.elements.count > 1 %>
    <div class="col-md-4 col-md-offset-1">
      <div class="row"><br>
        <div class="field field-element">
          <%= f.label :elemInitial %>:
          <%= f.collection_select(:elemInitial, @machine_status, :id, :nameElem, {}, {:class=>"form-control"}) %>
          <%= f.label :elemEnd %>
          <%= f.collection_select(:elemEnd, @machine_status, :id, :nameElem, {include_blank: true}, {:class=>"form-control"}) %>
        </div>
      </div>
    </div>
    <div class="col-md-8 col-md-offset-1">
      <hr>
    </div>
    <% end %>
    <div class="col-md-12">
      <div class="row">
        <div id="elements" class="col-md-8 col-md-offset-1 padding-element">
          <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modalElement" id="btnElemen">
            <%= t('buttons.new_element') %>
          </button>
          <%= f.submit class:'btn btn-primary' %>

        <% if @machine.elements.count > 1 %>
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modalTransition" id="btnTransition">
              <%= t('buttons.new_transition') %>
            </button>
        <% else %>
            <button type="button" class="btn btn-success btn-lg disabled" data-toggle="modal" data-target="">
              <%= t('buttons.new_transition') %>
            </button>
        <% end %>
        </div>
      </div><br>
    </div>
    <div class="col-md-8 col-md-offset-1">
      <div class="row">
        <div class="field hide">
          <%= f.label :user_id %><br>
          <%= f.text_field :user_id, :value => current_user.id, readonly: true %>
        </div>
      </div>
    </div>
  <% end %>

<!-- Tabela dos elementos e transições -->
<%= render partial: 'state/machines/shared/table' %>

<!-- Modal Elemento -->
<%= render partial: 'state/machines/modals/modalElementCreate' %>

<!-- Modal Transição -->
<%= render partial: 'state/machines/modals/modalTransitionCreate' %>

<!-- Modal Diagrama -->
<%= render partial: 'state/machines/modals/modalGerenateDiagram' %>

<script>
  $('#btnElemen').focus();
</script>

app/views/state/machines/index.html.erb
<h1><%= t('messages.diagrams') %></h1>

<%= link_to "#{t('buttons.new_diagram')}", new_state_machine_path, class:'btn btn-primary btn-xs pull-right' %> <br><br>

<table class="table">
  <thead>
    <tr>
      <th><%= @machines.model.human_attribute_name('nameDiagram') %></th>
      <th><%= @machines.model.human_attribute_name('created_at') %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= link_to "#{machine.nameDiagram}", edit_state_machine_path(machine) %></td>
        <td><%= machine.created_at %></td>
        <td><%= link_to "#{t('buttons.show')}", state_machine_path(machine) %></td>
        <td><%= link_to "#{t('buttons.destroy')}", state_machine_path(machine), method: :delete, data: { confirm: "#{t('messages.confirm_destroy')}" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/state/machines/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= t('messages.new_diagram') %></h1>

    <%= form_for([:state, @machine]) do |f| %>
      <% if @machine.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

          <ul>
          <% @machine.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :nameDiagram %><br>
        <%= f.text_field :nameDiagram, class:"form-control", placeholder:t('placeholder.name_diagram'), autofocus: true %>
      </div>
      <div class="field hide">
        <%= f.label :user_id %><br>
        <%= f.text_field :user_id, :value => current_user.id, readonly: true %>
      </div><br>
      <div class="actions">
        <%= f.submit class:'btn btn-primary btn-sm' %>
      </div>
    <% end %>
  </div>
</div>

app/views/state/machines/show.html.erb
<%= render partial: 'state/machines/shared/table' %>