config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :case do
    get 'home', to: 'home#index'
    resources :cases
    resources :components, only: [:create, :update, :destroy]
    resources :relations, only: [:create, :update, :destroy]
  end

  namespace :state do
    get 'home', to: 'home#index'
    resources :machines
    resources :transitions, only: [:create, :update, :destroy]
    resources :elements, only: [:create, :update, :destroy]
  end

  devise_for :users

end

app/models/case.rb
class Case < ActiveRecord::Base
  belongs_to :user
  has_many :components
  has_many :relations
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :case
  belongs_to :mold
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  has_many :relations
end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :machine
  belongs_to :type
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  belongs_to :user
  has_many :elements
  has_many :transitions
end

app/models/mold.rb
class Mold < ActiveRecord::Base
  has_many :components
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :case
  belongs_to :connection
end

app/models/transition.rb
class Transition < ActiveRecord::Base
  belongs_to :machines
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Associações
  has_many :machine
  has_many :case_diagrams

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set Layout
  layout :layout_by_resource

  protected
    def layout_by_resource
    if devise_controller? && resource_name == :user
      "application_devise"
    else
      "application"
    end
  end
end

app/controllers/case_controller.rb
class CaseController < ApplicationController
  layout 'casediagram'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/state/machines_controller.rb
class State::MachinesController < StateController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]
  before_action :config_table, only: [:show, :edit]

  def index
    @machines = Machine.where(user_id: current_user)
  end

  def show
  end

  def new
    @machine = Machine.new
  end

  def edit
    @machine_status = @machine.elements.where(type_id: 1)
  end

  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to edit_state_machine_path(@machine), notice: 'Diagrama criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to edit_state_machine_path(@machine), notice: 'Diagrama atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    if @machine.destroy
      respond_to do |format|
        format.html { redirect_to state_machines_path, notice: 'Diagrama deletado com sucesso.' }
      end
    end
  end

  private
    def set_machine
      @machine = Machine.find(params[:id])
    end

    def machine_params
      params.require(:machine).permit(:nameDiagram, :elemInitial, :elemEnd, :user_id)
    end

    def config_table
      @options_type = Type.all
      @options_elements = Element.where(machine_id: @machine.id)
    end
end

app/controllers/state_controller.rb
class StateController < ApplicationController
  layout 'statediagram'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case/actors_helper.rb
module Case::ActorsHelper
end

app/helpers/case/collies_helper.rb
module Case::ColliesHelper
end

app/helpers/case/diagrams_helper.rb
module Case::DiagramsHelper
end

app/helpers/case/home_helper.rb
module Case::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/state/home_helper.rb
module State::HomeHelper
end

app/views/state/machines/modals/_modalElementCreate.html.erb
<div class="modal fade" id="modalElement" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('messages.new_element') %></h4>
      </div>

      <%= form_tag(state_elements_path, method: 'post', class:"form-inline") do %>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12 text-center">
            <div class="form-group">
              <%= label_tag :type_id %><br>
              <%= select_tag(:type_id, options_from_collection_for_select(@options_type, "id", "name"), class: 'form-control', id: 'targetElement') %>
            </div>
            <div class="form-group">
              <%= label_tag :nameElem %><br>
              <%= text_field_tag :nameElem,nil,class:"form-control text-description" %>
            </div>
            <div class="form-group">
              <%= label_tag :descriptionElem %><br>
              <%= text_field_tag :descriptionElem,nil,class:"form-control text-description" %>
            </div>
            <div class="form-group hide">
              <%= text_field_tag :machine_id, @machine.id, class:"form-control", readonly: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag "#{t('buttons.save')}", class:"btn btn-primary btn-modal-element" %>
      </div>
      <% end %>

    </div>
  </div>
</div>


app/views/state/machines/modals/_modalElementEdit.html.erb
<div class="modal fade" id="modalEditElement" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editando Elemento</h4>
      </div>

      <%= form_tag(state_element_path, method: 'put', class:"form-inline", id:'formElementEdit') do %>
      <div class="modal-body text-center">
        <div class="form-group">
          <%= label_tag :nameElem %><br>
          <%= text_field_tag :nameElem,nil,class:"form-control",id:'nameElem' %>
        </div>
        <div class="form-group">
          <%= label_tag :descriptionElem %><br>
          <%= text_field_tag :descriptionElem,nil,class:"form-control",id:'descriptionElem' %>
        </div>
        <div class="form-group hide">
          <%= text_field_tag :type_id, nil, class:"form-control", readonly: true,id:'type_id' %>
          <%= text_field_tag :machine_id, nil, class:"form-control", readonly: true,id:'machine_id' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger pull-left" onclick="ElementDestroy()"><%= t('buttons.destroy') %></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag "#{t('buttons.save')}", class:"btn btn-primary btn-modal-element" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/state/machines/modals/_modalGerenateDiagram.html.erb
<div class="modal fade" id="modalDiagrama" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('messages.generate_diagram') %></h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/state/machines/modals/_modalTransitionCreate.html.erb
<div class="modal fade" id="modalTransition" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('messages.new_transition') %></h4>
      </div>

      <%= form_tag(state_transitions_path, method: 'post', class:"form-inline") do %>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12 text-center">
            <div class="form-group">
              <%= label_tag :elemStart %><br>
              <%= select_tag(:elemStart, options_from_collection_for_select(@options_elements, "id", "nameElem"), class:'form-control', id:'targetTransition') %>
            </div>
            <div class="form-group">
            <%= label_tag :elemEnd %><br>
              <%= select_tag(:elemEnd, options_from_collection_for_select(@options_elements, "id", "nameElem"), class: 'form-control') %>
            </div>
            <div class="form-group">
              <%= label_tag :descriptionTran %><br>
              <%= text_field_tag :descriptionTran,nil,class:"form-control text-description" %>
            </div>
            <div class="form-group hide">
              <%= text_field_tag :machine_id, @machine.id, class:"form-control", readonly: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag "#{t('buttons.save')}", class:"btn btn-primary btn-modal-transition" %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/state/machines/modals/_modalTransitionEdit.html.erb
<div class="modal fade" id="modalEditTransition" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editando Transição</h4>
      </div>

      <%= form_tag(state_transition_path, method: 'put', class:"form-inline", id:'formTransitionEdit') do %>
      <div class="modal-body text-center">
        <div class="form-group">
          <%= label_tag :elemStart %><br>
          <%= select_tag(:elemStart, options_from_collection_for_select(@options_elements, "id", "nameElem"), class:'form-control', id:'elemStart') %>
        </div>
        <div class="form-group">
        <%= label_tag :elemEnd %><br>
          <%= select_tag(:elemEnd, options_from_collection_for_select(@options_elements, "id", "nameElem"), class: 'form-control', id:'elemEnd') %>
        </div>
        <div class="form-group">
          <%= label_tag :descriptionTran %><br>
          <%= text_field_tag :descriptionTran,nil,class:"form-control text-description", id:'descriptionTran' %>
        </div>
        <div class="form-group hide">
          <%= text_field_tag :machine_id, nil, class:"form-control", readonly: true, id:'machine_id' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger pull-left" onclick="TransitionDestroy()"><%= t('buttons.destroy') %></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag "#{t('buttons.save')}", class:"btn btn-primary btn-modal-element" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/state/machines/shared/_table.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-1">

<hr>

    <table class="data-table">
      <thead>
        <th>Elemento Tipo</th>
        <th>Elemento Nome</th>
        <th>Elemento Descrição</th>
      </thead>
      <tbody>
          <% @machine.elements.each do |item| %>
            <tr onclick="showModal('Element'); captureAttributesElement('<%= item.id %>', '<%= item.nameElem %>', '<%= item.descriptionElem %>', '<%= item.machine_id %>', '<%= item.type_id %>'); focusEditElement(); alterIdElement('<%= item.id %>');">
              <td><%= item.type_id %></td>
              <td><%= item.nameElem %></td>
              <td><%= item.descriptionElem %></td>
            </tr>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">

<hr>

    <table class="data-table">
      <thead>
        <th>Transição Incial</th>
        <th>Transição Final</th>
        <th>Transição Descrição</th>
      </thead>
      <tbody>
          <% @machine.transitions.each do |item| %>
            <tr onclick="showModal('Transition'); captureAttributesTransition('<%= item.id %>','<%= item.elemStart %>','<%= item.elemEnd %>','<%= item.descriptionTran %>','<%= item.machine_id %>'); focusEditTransition(); alterIdTransition('<%= item.id %>')">
              <td><%= item.elemStart %></td>
              <td><%= item.elemEnd %></td>
              <td><%= item.descriptionTran %></td>
            </tr>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<!-- Modal Edit Element -->
<%= render partial: 'state/machines/modals/modalElementEdit' %>

<!-- Modal Edit Transition -->
<%= render partial: 'state/machines/modals/modalTransitionEdit' %>

<script>
  // Variável com ID do Elemento e Transição a ser apagado.
  var idElement = 0;
  var idTransition = 0;

  // Função para exibir o modal de edição do elemento e transição.
  function showModal(arg) {
    $('#modalEdit' + arg).modal('show')
  };

  // Captura atributos do elemento ao clicar na linha da tabela.
  function captureAttributesElement(id, nameElem, descriptionElem, machine_id, type_id) {
    $('input#nameElem').val(nameElem);
    $('input#descriptionElem').val(descriptionElem);
    $('input#machine_id').val(machine_id);
    $('input#type_id').val(type_id);
    $("#formElementEdit").attr("action", "/state/elements/" + id);
  };

  // Captura atributos da transição ao clicar na linha da tabela.
  function captureAttributesTransition(id, elemStart, elemEnd, descriptionTran, machine_id) {
    $('select#elemStart').val(elemStart);
    $('select#elemEnd').val(elemEnd);
    $('input#descriptionTran').val(descriptionTran);
    $('input#machine_id').val(machine_id);
    $("#formTransitionEdit").attr("action", "/state/transitions/" + id);
  };

  // Função para focar o input#nameElem
  function focusEditElement() {
    setTimeout(function(){
        $('#nameElem').focus();
    }, 500);
  };

  // Função para focar o input#nameElem
  function focusEditTransition() {
    setTimeout(function(){
        $('#elemStart').focus();
    }, 500);
  };

  // Função para alterar o valor da variável com a ID do elemento
  // que o usuário clicou na tabela.
  function alterIdElement(id){
    idElement = id;
  };

  // Função para alterar o valor da variável com a ID da transição
  // que o usuário clicou na tabela.
  function alterIdTransition(id){
    idTransition = id;
  };

  // Função para apagar o elemento ao clicar no botão 'apagar'
  function ElementDestroy(){
    $("#formElementDestroy").attr("action", "/state/elements/" + idElement);
    $('#formElementDestroy').submit();
  };

  // Função para apagar o transição ao clicar no botão 'apagar'
  function TransitionDestroy(){
    $("#formTransitionDestroy").attr("action", "/state/transitions/" + idTransition);
    $('#formTransitionDestroy').submit();
  };

</script>

<!-- Formulário para apagar um elemento. -->
<%= form_tag(state_element_path, method: 'delete', class:"form-inline", id:'formElementDestroy') do %>
<% end %>

<!-- Formulário para apagar uma transição. -->
<%= form_tag(state_transition_path, method: 'delete', class:"form-inline", id:'formTransitionDestroy') do %>
<% end %>