config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :case do
    get 'home', to: 'home#index'
    resources :cases
    resources :components, only: [:create, :update, :destroy]
    resources :relations, only: [:create, :update, :destroy]
  end

  namespace :state do
    get 'home', to: 'home#index'
    resources :machines
    resources :transitions, only: [:create, :update, :destroy]
    resources :elements, only: [:create, :update, :destroy]
  end

  devise_for :users

end

app/models/case.rb
class Case < ActiveRecord::Base
  belongs_to :user
  has_many :components
  has_many :relations
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :case
  belongs_to :mold
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  has_many :relations
end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :machine
  belongs_to :type
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  belongs_to :user
  has_many :elements
  has_many :transitions
end

app/models/mold.rb
class Mold < ActiveRecord::Base
  has_many :components
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :case
  belongs_to :connection
end

app/models/transition.rb
class Transition < ActiveRecord::Base
  belongs_to :machines
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Associações
  has_many :machine
  has_many :case_diagrams

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set Layout
  layout :layout_by_resource

  protected
    def layout_by_resource
    if devise_controller? && resource_name == :user
      "application_devise"
    else
      "application"
    end
  end
end

app/controllers/case/cases_controller.rb
class Case::CasesController < CaseController
  before_action :set_case_case, only: [:show, :edit, :update, :destroy]
  before_action :config_table, only: [:show, :edit]

  def index
    @cases = Case.where(user_id: current_user)
  end

  def show
  end

  def new
    @case = Case.new
  end

  def edit
    @count_actors = @case.components.where(mold_id: 1).count
    @count_cases = @case.components.where(mold_id: 2).count
  end

  def create
    @case = Case.new(case_params)

    respond_to do |format|
      if @case.save
        format.html { redirect_to edit_case_case_path(@case), notice: 'Diagrama criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @case.update(case_params)
        format.html { redirect_to edit_case_case_path(@case), notice: 'Diagrama atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @case.destroy
    respond_to do |format|
      format.html { redirect_to case_cases_path, notice: 'Diagrama deletado com sucesso.' }
    end
  end

  private
    def set_case_case
      @case = Case.find(params[:id])
    end

    def case_params
      params.require(:case).permit(:namediagram, :user_id)
    end

    def config_table
      @options_connections = Connection.all
      @options_molds = Mold.all
      @options_components = Component.where(case_id: @case.id)
    end
end

app/controllers/case_controller.rb
class CaseController < ApplicationController
  layout 'casediagram'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/state_controller.rb
class StateController < ApplicationController
  layout 'statediagram'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case/actors_helper.rb
module Case::ActorsHelper
end

app/helpers/case/collies_helper.rb
module Case::ColliesHelper
end

app/helpers/case/home_helper.rb
module Case::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/state/home_helper.rb
module State::HomeHelper
end

app/views/case/cases/modals/_modalComponentCreate.html.erb
<div class="modal fade" id="modalComponent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('messages.new_component') %></h4>
      </div>

      <%= form_tag(case_components_path, method: 'post', class:"form-inline") do %>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12 text-center">
            <div class="form-group">
              <%= label_tag :mold_id %><br>
              <%= select_tag(:mold_id, options_from_collection_for_select(@options_molds, "id", "name"), class: 'form-control', id:'targetComponent') %>
            </div>
            <div class="form-group">
              <%= label_tag :descriptionsComponent %><br>
              <%= text_field_tag :descriptionsComponent,nil,class:"form-control text-description" %>
            </div>
            <div class="form-group hide">
              <%= text_field_tag :case_id, @case.id, class:"form-control", readonly: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag "#{t('buttons.save')}", class:"btn btn-primary btn-modal-component" %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/case/cases/modals/_modalComponentEdit.html.erb
<div class="modal fade" id="modalEditComponent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editando Componente</h4>
      </div>

      <%= form_tag(case_component_path, method: 'put', class:"form-inline", id:'formComponentEdit') do %>
      <div class="modal-body text-center">
        <div class="form-group">
          <%= label_tag :descriptionsComponent %><br>
          <%= text_field_tag :descriptionsComponent,nil,class:"form-control",id:'descriptionComponent' %>
        </div>
        <div class="form-group hide">
          <%= text_field_tag :case_id,nil,class:"form-control", readonly: true, id:'case_id' %>
          <%= text_field_tag :mold_id,nil,class:"form-control", readonly: true, id:'mold_id' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger pull-left" onclick="ComponentDestroy()"><%= t('buttons.destroy') %></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag "#{t('buttons.save')}", class:"btn btn-primary btn-modal-element" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/case/cases/modals/_modalGerenateDiagram.html.erb
<div class="modal fade" id="modalDiagrama" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('messages.generate_diagram') %></h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/case/cases/modals/_modalRelationCreate.html.erb
<div class="modal fade" id="modalRelation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('messages.new_relation') %></h4>
      </div>
      <%= form_tag(case_relations_path, method: 'post', class:"form-inline") do %>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12 text-center">
            <div class="form-group">
              <%= label_tag :connection_id %><br>
              <%= select_tag(:connection_id, options_from_collection_for_select(@options_connections, "id", "name"), class: 'form-control', id:'targetRelation') %>
            </div>
            <div class="form-group">
              <%= label_tag :elemStart %><br>
              <%= select_tag(:elemStart, options_from_collection_for_select(@options_components, "id", "descriptionsComponent"), class: 'form-control') %>
            </div>
            <div class="form-group">
              <%= label_tag :elemEnd %><br>
              <%= select_tag(:elemEnd, options_from_collection_for_select(@options_components, "id", "descriptionsComponent"), class: 'form-control') %>
            </div>
            <div class="form-group hide">
              <%= text_field_tag :case_id, @case.id, class:"form-control", readonly: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag "#{t('buttons.save')}", class:"btn btn-primary btn-modal-relation"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/case/cases/modals/_modalRelationEdit.html.erb
<div class="modal fade" id="modalEditRelation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editando Elemento</h4>
      </div>

      <%= form_tag(case_relation_path, method: 'put', class:"form-inline", id:'formRelationEdit') do %>
      <div class="modal-body text-center">
        <div class="form-group">
          <%= label_tag :connection_id %><br>
          <%= select_tag(:connection_id, options_from_collection_for_select(@options_connections, "id", "name"), class:'form-control', id:'connection_id') %>
        </div>
      <div class="form-group">
          <%= label_tag :elemStart %><br>
          <%= select_tag(:elemStart, options_from_collection_for_select(@options_components, "id", "descriptionsComponent"), class:'form-control', id:'elemStart') %>
        </div>
        <div class="form-group">
          <%= label_tag :elemEnd %><br>
          <%= select_tag(:elemEnd, options_from_collection_for_select(@options_components, "id", "descriptionsComponent"), class:'form-control', id:'elemEnd') %>
        </div>
        <div class="form-group hide">
          <%= text_field_tag :case_id, nil, class:"form-control", readonly: true,id:'case_id' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger pull-left" onclick="RelationDestroy()"><%= t('buttons.destroy') %></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag "#{t('buttons.save')}", class:"btn btn-primary btn-modal-element" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/case/cases/shared/_table.html.erb
  <div class="row">
    <div class="col-md-4 col-md-offset-1">

<hr>

      <table class="data-table">
        <thead>
          <th>Elemento Tipo</th>
          <th>Elemento Descrição</th>
        </thead>
        <tbody>
            <% @case.components.each do |item| %>
              <tr onclick="showModal('Component'); captureAttributesComponent('<%= item.id %>', '<%= item.descriptionsComponent %>', '<%= item.case_id %>', '<%= item.mold_id %>'); focusEditComponent(); alterIdComponent('<%= item.id %>');">
                <td><%= item.mold_id %></td>
                <td><%= item.descriptionsComponent %></td>
              </tr>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-4">

<hr>

      <table class="data-table">
        <thead>
          <th>Tipo</th>
          <th>Incial</th>
          <th>Final</th>
        </thead>
        <tbody>
            <% @case.relations.each do |item| %>
              <tr onclick="showModal('Relation'); captureAttributesRelation('<%= item.id %>','<%= item.elemStart %>','<%= item.elemEnd %>', '<%= item.case_id %>', '<%= item.connection_id %>'); focusEditRelation(); alterIdRelation('<%= item.id %>');">
                <td><%= item.connection_id %></td>
                <td><%= item.elemStart %></td>
                <td><%= item.elemEnd %></td>
              </tr>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

<!-- Modal Edit Component -->
<%= render partial: 'case/cases/modals/modalComponentEdit' %>

<!-- Modal Edit Relation -->
<%= render partial: 'case/cases/modals/modalRelationEdit' %>

<script>
  // Variável com ID do Componente e Relação a ser apagado.
  var idComponent = 0;
  var idRelation = 0;

  // Função para exibir o modal de edição de Componente e Relação.
  function showModal(arg) {
    $('#modalEdit' + arg).modal('show')
  };

  // Capturar atributos do Componente ao clicar na linha da tabela.
  function captureAttributesComponent(id, descriptionComponent, case_id, mold_id) {
    $('input#descriptionComponent').val(descriptionComponent);
    $('input#case_id').val(case_id);
    $('input#mold_id').val(mold_id);
    $("#formComponentEdit").attr("action", "/case/components/" + id);
  };

  // Capturar atributos da Relação ao clicar na linha da tabela.
  function captureAttributesRelation(id, elemStart, elemEnd, case_id, connection_id) {
    $('select#elemStart').val(elemStart);
    $('select#elemEnd').val(elemEnd);
    $('input#case_id').val(case_id);
    $('select#connection_id').val(connection_id);
    $("#formRelationEdit").attr("action", "/case/relations/" + id);
  };

  // Função para focar o input#descriptionComponent
  function focusEditComponent() {
    setTimeout(function(){
        $('#descriptionComponent').focus();
    }, 500);
  };

  // Função para focar o input#elemStart
  function focusEditRelation() {
    setTimeout(function(){
        $('#connection_id').focus();
    }, 500);
  };

  // Função para alterar o valor da variável com a ID do componente
  // que o usuário clicou na tabela.
  function alterIdComponent(id){
    idComponent = id;
  };

  // Função para alterar o valor da variável com a ID da relação
  // que o usuário clicou na tabela.
  function alterIdRelation(id){
    idRelation = id;
  };

  // Função para apagar o componente ao clicar no botão 'apagar'
  function ComponentDestroy(){
    $("#formComponentDestroy").attr("action", "/case/components/" + idComponent);
    $('#formComponentDestroy').submit();
  };

  // Função para apagar a relação ao clicar no botão 'apagar'
  function RelationDestroy(){
    $("#formRelationDestroy").attr("action", "/case/relations/" + idRelation);
    $('#formRelationDestroy').submit();
  };

</script>

<!-- Formulário para apagar um componente. -->
<%= form_tag(case_component_path, method: 'delete', class:"form-inline", id:'formComponentDestroy') do %>
<% end %>

<!-- Formulário para apagar uma relação. -->
<%= form_tag(case_relation_path, method: 'delete', class:"form-inline", id:'formRelationDestroy') do %>
<% end %>